# -*- coding: utf-8 -*-
# The SPHY model Pre-Processor interface plugin for QGIS:
# A QGIS plugin that allows the user to create SPHY model input data based on a database. 
#
# Copyright (C) 2015  Wilco Terink
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Email: terinkw@gmail.com

#-Authorship information-###################################################################
__author__ = "Wilco Terink"
__copyright__ = "Wilco Terink"
__license__ = "GPL"
__version__ = "1.0.0"
__email__ = "terinkw@gmail.com"
__date__ ='1 January 2017'
############################################################################################

# Form implementation generated from reading ui file 'SPHY_preprocess_dialog_base.ui'
#
# Created: Tue Oct 06 16:22:10 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SphyPreProcessDialog(object):
    def setupUi(self, SphyPreProcessDialog):
        SphyPreProcessDialog.setObjectName(_fromUtf8("SphyPreProcessDialog"))
        SphyPreProcessDialog.resize(699, 429)
        self.Tab = QtGui.QTabWidget(SphyPreProcessDialog)
        self.Tab.setEnabled(True)
        self.Tab.setGeometry(QtCore.QRect(9, 50, 681, 371))
        self.Tab.setObjectName(_fromUtf8("Tab"))
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName(_fromUtf8("generalTab"))
        self.foldersGroupBox = QtGui.QGroupBox(self.generalTab)
        self.foldersGroupBox.setGeometry(QtCore.QRect(9, 9, 661, 121))
        self.foldersGroupBox.setObjectName(_fromUtf8("foldersGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.foldersGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.databaseLabel = QtGui.QLabel(self.foldersGroupBox)
        self.databaseLabel.setObjectName(_fromUtf8("databaseLabel"))
        self.horizontalLayout_2.addWidget(self.databaseLabel)
        self.databaseLineEdit = QtGui.QLineEdit(self.foldersGroupBox)
        self.databaseLineEdit.setReadOnly(True)
        self.databaseLineEdit.setObjectName(_fromUtf8("databaseLineEdit"))
        self.horizontalLayout_2.addWidget(self.databaseLineEdit)
        self.databaseFolderButton = QtGui.QToolButton(self.foldersGroupBox)
        self.databaseFolderButton.setObjectName(_fromUtf8("databaseFolderButton"))
        self.horizontalLayout_2.addWidget(self.databaseFolderButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.processedModelDataLabel = QtGui.QLabel(self.foldersGroupBox)
        self.processedModelDataLabel.setObjectName(_fromUtf8("processedModelDataLabel"))
        self.horizontalLayout.addWidget(self.processedModelDataLabel)
        self.resultsLineEdit = QtGui.QLineEdit(self.foldersGroupBox)
        self.resultsLineEdit.setReadOnly(True)
        self.resultsLineEdit.setObjectName(_fromUtf8("resultsLineEdit"))
        self.horizontalLayout.addWidget(self.resultsLineEdit)
        self.resultsFolderButton = QtGui.QToolButton(self.foldersGroupBox)
        self.resultsFolderButton.setObjectName(_fromUtf8("resultsFolderButton"))
        self.horizontalLayout.addWidget(self.resultsFolderButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pcrasterBinFolderLabel = QtGui.QLabel(self.foldersGroupBox)
        self.pcrasterBinFolderLabel.setObjectName(_fromUtf8("pcrasterBinFolderLabel"))
        self.horizontalLayout_13.addWidget(self.pcrasterBinFolderLabel)
        self.pcrasterBinFolderLineEdit = QtGui.QLineEdit(self.foldersGroupBox)
        self.pcrasterBinFolderLineEdit.setReadOnly(True)
        self.pcrasterBinFolderLineEdit.setObjectName(_fromUtf8("pcrasterBinFolderLineEdit"))
        self.horizontalLayout_13.addWidget(self.pcrasterBinFolderLineEdit)
        self.pcrasterBinFolderButton = QtGui.QToolButton(self.foldersGroupBox)
        self.pcrasterBinFolderButton.setObjectName(_fromUtf8("pcrasterBinFolderButton"))
        self.horizontalLayout_13.addWidget(self.pcrasterBinFolderButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.periodProcessGroupBox = QtGui.QGroupBox(self.generalTab)
        self.periodProcessGroupBox.setGeometry(QtCore.QRect(9, 240, 308, 55))
        self.periodProcessGroupBox.setObjectName(_fromUtf8("periodProcessGroupBox"))
        self.horizontalLayout_84 = QtGui.QHBoxLayout(self.periodProcessGroupBox)
        self.horizontalLayout_84.setObjectName(_fromUtf8("horizontalLayout_84"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.startDateLabel = QtGui.QLabel(self.periodProcessGroupBox)
        self.startDateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startDateLabel.setObjectName(_fromUtf8("startDateLabel"))
        self.horizontalLayout_4.addWidget(self.startDateLabel)
        self.startDateEdit = QtGui.QDateEdit(self.periodProcessGroupBox)
        self.startDateEdit.setObjectName(_fromUtf8("startDateEdit"))
        self.horizontalLayout_4.addWidget(self.startDateEdit)
        self.endDateLabel = QtGui.QLabel(self.periodProcessGroupBox)
        self.endDateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.endDateLabel.setObjectName(_fromUtf8("endDateLabel"))
        self.horizontalLayout_4.addWidget(self.endDateLabel)
        self.endDateEdit = QtGui.QDateEdit(self.periodProcessGroupBox)
        self.endDateEdit.setDate(QtCore.QDate(2005, 12, 31))
        self.endDateEdit.setObjectName(_fromUtf8("endDateEdit"))
        self.horizontalLayout_4.addWidget(self.endDateEdit)
        self.horizontalLayout_84.addLayout(self.horizontalLayout_4)
        self.coordinateSystemGroupBox = QtGui.QGroupBox(self.generalTab)
        self.coordinateSystemGroupBox.setGeometry(QtCore.QRect(9, 140, 661, 91))
        self.coordinateSystemGroupBox.setObjectName(_fromUtf8("coordinateSystemGroupBox"))
        self.utmInfoLineEdit = QtGui.QPlainTextEdit(self.coordinateSystemGroupBox)
        self.utmInfoLineEdit.setGeometry(QtCore.QRect(240, 23, 411, 61))
        self.utmInfoLineEdit.setReadOnly(True)
        self.utmInfoLineEdit.setObjectName(_fromUtf8("utmInfoLineEdit"))
        self.layoutWidget = QtGui.QWidget(self.coordinateSystemGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 23, 221, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.utmLabel = QtGui.QLabel(self.layoutWidget)
        self.utmLabel.setObjectName(_fromUtf8("utmLabel"))
        self.horizontalLayout_5.addWidget(self.utmLabel)
        self.utmSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.utmSpinBox.setMinimum(1)
        self.utmSpinBox.setMaximum(60)
        self.utmSpinBox.setProperty("value", 60)
        self.utmSpinBox.setObjectName(_fromUtf8("utmSpinBox"))
        self.horizontalLayout_5.addWidget(self.utmSpinBox)
        self.utmNRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.utmNRadioButton.setChecked(False)
        self.utmNRadioButton.setObjectName(_fromUtf8("utmNRadioButton"))
        self.horizontalLayout_5.addWidget(self.utmNRadioButton)
        self.utmSRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.utmSRadioButton.setChecked(True)
        self.utmSRadioButton.setObjectName(_fromUtf8("utmSRadioButton"))
        self.horizontalLayout_5.addWidget(self.utmSRadioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.showUTMMapButton = QtGui.QToolButton(self.layoutWidget)
        self.showUTMMapButton.setObjectName(_fromUtf8("showUTMMapButton"))
        self.verticalLayout_3.addWidget(self.showUTMMapButton)
        self.label_3 = QtGui.QLabel(self.generalTab)
        self.label_3.setGeometry(QtCore.QRect(520, 240, 151, 101))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/SphyPreProcess/icon.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Tab.addTab(self.generalTab, _fromUtf8(""))
        self.areaSelectionTab = QtGui.QWidget()
        self.areaSelectionTab.setObjectName(_fromUtf8("areaSelectionTab"))
        self.selectAreagroupBox = QtGui.QGroupBox(self.areaSelectionTab)
        self.selectAreagroupBox.setGeometry(QtCore.QRect(9, 9, 181, 331))
        self.selectAreagroupBox.setAutoFillBackground(True)
        self.selectAreagroupBox.setObjectName(_fromUtf8("selectAreagroupBox"))
        self.selectAreaButton = QtGui.QToolButton(self.selectAreagroupBox)
        self.selectAreaButton.setGeometry(QtCore.QRect(10, 48, 157, 123))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.selectAreaButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.selectAreaButton.setFont(font)
        self.selectAreaButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectAreaButton.setMouseTracking(False)
        self.selectAreaButton.setAutoFillBackground(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/SphyPreProcess/select_area.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectAreaButton.setIcon(icon)
        self.selectAreaButton.setIconSize(QtCore.QSize(150, 150))
        self.selectAreaButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.selectAreaButton.setObjectName(_fromUtf8("selectAreaButton"))
        self.showBackgroundMapcheckBox = QtGui.QCheckBox(self.selectAreagroupBox)
        self.showBackgroundMapcheckBox.setGeometry(QtCore.QRect(11, 24, 158, 17))
        self.showBackgroundMapcheckBox.setObjectName(_fromUtf8("showBackgroundMapcheckBox"))
        self.areaPropertiesGroupBox = QtGui.QGroupBox(self.areaSelectionTab)
        self.areaPropertiesGroupBox.setEnabled(True)
        self.areaPropertiesGroupBox.setGeometry(QtCore.QRect(200, 9, 471, 331))
        self.areaPropertiesGroupBox.setObjectName(_fromUtf8("areaPropertiesGroupBox"))
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.areaPropertiesGroupBox)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 51, 215, 22))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.areaSizeLabel = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.areaSizeLabel.setObjectName(_fromUtf8("areaSizeLabel"))
        self.horizontalLayout_9.addWidget(self.areaSizeLabel)
        self.areaSizeLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        self.areaSizeLineEdit.setReadOnly(True)
        self.areaSizeLineEdit.setObjectName(_fromUtf8("areaSizeLineEdit"))
        self.horizontalLayout_9.addWidget(self.areaSizeLineEdit)
        self.horizontalLayoutWidget_9 = QtGui.QWidget(self.areaPropertiesGroupBox)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 79, 451, 22))
        self.horizontalLayoutWidget_9.setObjectName(_fromUtf8("horizontalLayoutWidget_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.xminLabel = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.xminLabel.setObjectName(_fromUtf8("xminLabel"))
        self.horizontalLayout_8.addWidget(self.xminLabel)
        self.xminLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_9)
        self.xminLineEdit.setReadOnly(True)
        self.xminLineEdit.setObjectName(_fromUtf8("xminLineEdit"))
        self.horizontalLayout_8.addWidget(self.xminLineEdit)
        self.xmaxLabel = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.xmaxLabel.setObjectName(_fromUtf8("xmaxLabel"))
        self.horizontalLayout_8.addWidget(self.xmaxLabel)
        self.xmaxLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_9)
        self.xmaxLineEdit.setReadOnly(True)
        self.xmaxLineEdit.setObjectName(_fromUtf8("xmaxLineEdit"))
        self.horizontalLayout_8.addWidget(self.xmaxLineEdit)
        self.columnsLabel = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.columnsLabel.setObjectName(_fromUtf8("columnsLabel"))
        self.horizontalLayout_8.addWidget(self.columnsLabel)
        self.columnsLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_9)
        self.columnsLineEdit.setReadOnly(True)
        self.columnsLineEdit.setObjectName(_fromUtf8("columnsLineEdit"))
        self.horizontalLayout_8.addWidget(self.columnsLineEdit)
        self.horizontalLayoutWidget_10 = QtGui.QWidget(self.areaPropertiesGroupBox)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 107, 451, 22))
        self.horizontalLayoutWidget_10.setObjectName(_fromUtf8("horizontalLayoutWidget_10"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.yminLabel = QtGui.QLabel(self.horizontalLayoutWidget_10)
        self.yminLabel.setObjectName(_fromUtf8("yminLabel"))
        self.horizontalLayout_10.addWidget(self.yminLabel)
        self.yminLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_10)
        self.yminLineEdit.setReadOnly(True)
        self.yminLineEdit.setObjectName(_fromUtf8("yminLineEdit"))
        self.horizontalLayout_10.addWidget(self.yminLineEdit)
        self.ymaxLabel = QtGui.QLabel(self.horizontalLayoutWidget_10)
        self.ymaxLabel.setObjectName(_fromUtf8("ymaxLabel"))
        self.horizontalLayout_10.addWidget(self.ymaxLabel)
        self.ymaxLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_10)
        self.ymaxLineEdit.setReadOnly(True)
        self.ymaxLineEdit.setObjectName(_fromUtf8("ymaxLineEdit"))
        self.horizontalLayout_10.addWidget(self.ymaxLineEdit)
        self.rowsLabel = QtGui.QLabel(self.horizontalLayoutWidget_10)
        self.rowsLabel.setObjectName(_fromUtf8("rowsLabel"))
        self.horizontalLayout_10.addWidget(self.rowsLabel)
        self.rowsLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_10)
        self.rowsLineEdit.setReadOnly(True)
        self.rowsLineEdit.setObjectName(_fromUtf8("rowsLineEdit"))
        self.horizontalLayout_10.addWidget(self.rowsLineEdit)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.areaPropertiesGroupBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(240, 50, 221, 22))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.numberCellsLabel = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.numberCellsLabel.setObjectName(_fromUtf8("numberCellsLabel"))
        self.horizontalLayout_6.addWidget(self.numberCellsLabel)
        self.numberCellsLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.numberCellsLineEdit.setReadOnly(True)
        self.numberCellsLineEdit.setObjectName(_fromUtf8("numberCellsLineEdit"))
        self.horizontalLayout_6.addWidget(self.numberCellsLineEdit)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.areaPropertiesGroupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 135, 451, 22))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.spatialResolutionLabel = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.spatialResolutionLabel.setObjectName(_fromUtf8("spatialResolutionLabel"))
        self.horizontalLayout_3.addWidget(self.spatialResolutionLabel)
        self.spatialResolutionSpinBox = QtGui.QSpinBox(self.horizontalLayoutWidget_4)
        self.spatialResolutionSpinBox.setMaximum(100000)
        self.spatialResolutionSpinBox.setSingleStep(10)
        self.spatialResolutionSpinBox.setProperty("value", 500)
        self.spatialResolutionSpinBox.setObjectName(_fromUtf8("spatialResolutionSpinBox"))
        self.horizontalLayout_3.addWidget(self.spatialResolutionSpinBox)
        self.calculateAreaPropsButton = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        self.calculateAreaPropsButton.setObjectName(_fromUtf8("calculateAreaPropsButton"))
        self.horizontalLayout_3.addWidget(self.calculateAreaPropsButton)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.areaPropertiesGroupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 23, 451, 22))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.selectedAreaMapLabel = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.selectedAreaMapLabel.setObjectName(_fromUtf8("selectedAreaMapLabel"))
        self.horizontalLayout_11.addWidget(self.selectedAreaMapLabel)
        self.selectedAreaMapLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.selectedAreaMapLineEdit.setReadOnly(True)
        self.selectedAreaMapLineEdit.setObjectName(_fromUtf8("selectedAreaMapLineEdit"))
        self.horizontalLayout_11.addWidget(self.selectedAreaMapLineEdit)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.areaPropertiesGroupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 160, 451, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.createModelCloneButton = QtGui.QToolButton(self.horizontalLayoutWidget_3)
        self.createModelCloneButton.setObjectName(_fromUtf8("createModelCloneButton"))
        self.horizontalLayout_12.addWidget(self.createModelCloneButton)
        self.cloneLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.cloneLineEdit.setReadOnly(True)
        self.cloneLineEdit.setObjectName(_fromUtf8("cloneLineEdit"))
        self.horizontalLayout_12.addWidget(self.cloneLineEdit)
        self.Tab.addTab(self.areaSelectionTab, _fromUtf8(""))
        self.modulesTab = QtGui.QWidget()
        self.modulesTab.setObjectName(_fromUtf8("modulesTab"))
        self.modulesGroupBox = QtGui.QGroupBox(self.modulesTab)
        self.modulesGroupBox.setGeometry(QtCore.QRect(11, 11, 138, 331))
        self.modulesGroupBox.setObjectName(_fromUtf8("modulesGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.modulesGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.glacierModCheckBox = QtGui.QCheckBox(self.modulesGroupBox)
        self.glacierModCheckBox.setObjectName(_fromUtf8("glacierModCheckBox"))
        self.verticalLayout.addWidget(self.glacierModCheckBox)
        self.snowModCheckBox = QtGui.QCheckBox(self.modulesGroupBox)
        self.snowModCheckBox.setObjectName(_fromUtf8("snowModCheckBox"))
        self.verticalLayout.addWidget(self.snowModCheckBox)
        self.groundwaterModCheckBox = QtGui.QCheckBox(self.modulesGroupBox)
        self.groundwaterModCheckBox.setObjectName(_fromUtf8("groundwaterModCheckBox"))
        self.verticalLayout.addWidget(self.groundwaterModCheckBox)
        self.routingModCheckBox = QtGui.QCheckBox(self.modulesGroupBox)
        self.routingModCheckBox.setObjectName(_fromUtf8("routingModCheckBox"))
        self.verticalLayout.addWidget(self.routingModCheckBox)
        self.dynamicVegModCheckBox = QtGui.QCheckBox(self.modulesGroupBox)
        self.dynamicVegModCheckBox.setEnabled(False)
        self.dynamicVegModCheckBox.setObjectName(_fromUtf8("dynamicVegModCheckBox"))
        self.verticalLayout.addWidget(self.dynamicVegModCheckBox)
        self.lakesModCheckBox = QtGui.QCheckBox(self.modulesGroupBox)
        self.lakesModCheckBox.setEnabled(False)
        self.lakesModCheckBox.setObjectName(_fromUtf8("lakesModCheckBox"))
        self.verticalLayout.addWidget(self.lakesModCheckBox)
        self.reservorisModCheckBox = QtGui.QCheckBox(self.modulesGroupBox)
        self.reservorisModCheckBox.setEnabled(False)
        self.reservorisModCheckBox.setObjectName(_fromUtf8("reservorisModCheckBox"))
        self.verticalLayout.addWidget(self.reservorisModCheckBox)
        self.sedimentModCheckBox = QtGui.QCheckBox(self.modulesGroupBox)
        self.sedimentModCheckBox.setEnabled(False)
        self.sedimentModCheckBox.setObjectName(_fromUtf8("sedimentModCheckBox"))
        self.verticalLayout.addWidget(self.sedimentModCheckBox)
        self.mapsGroupBox = QtGui.QGroupBox(self.modulesTab)
        self.mapsGroupBox.setGeometry(QtCore.QRect(155, 11, 131, 331))
        self.mapsGroupBox.setObjectName(_fromUtf8("mapsGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.mapsGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.modulesListWidget = QtGui.QListWidget(self.mapsGroupBox)
        self.modulesListWidget.setObjectName(_fromUtf8("modulesListWidget"))
        self.verticalLayout_4.addWidget(self.modulesListWidget)
        self.processLog1GroupBox = QtGui.QGroupBox(self.modulesTab)
        self.processLog1GroupBox.setGeometry(QtCore.QRect(295, 11, 371, 331))
        self.processLog1GroupBox.setObjectName(_fromUtf8("processLog1GroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.processLog1GroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.processLog1TextEdit = QtGui.QTextEdit(self.processLog1GroupBox)
        self.processLog1TextEdit.setReadOnly(True)
        self.processLog1TextEdit.setObjectName(_fromUtf8("processLog1TextEdit"))
        self.gridLayout_3.addWidget(self.processLog1TextEdit, 0, 0, 1, 2)
        self.initialMapsProgressBar = QtGui.QProgressBar(self.processLog1GroupBox)
        self.initialMapsProgressBar.setProperty("value", 0)
        self.initialMapsProgressBar.setObjectName(_fromUtf8("initialMapsProgressBar"))
        self.gridLayout_3.addWidget(self.initialMapsProgressBar, 1, 0, 1, 1)
        self.createInitialMapsToolButton = QtGui.QToolButton(self.processLog1GroupBox)
        self.createInitialMapsToolButton.setObjectName(_fromUtf8("createInitialMapsToolButton"))
        self.gridLayout_3.addWidget(self.createInitialMapsToolButton, 1, 1, 1, 1)
        self.Tab.addTab(self.modulesTab, _fromUtf8(""))
        self.basinDelineationTab = QtGui.QWidget()
        self.basinDelineationTab.setObjectName(_fromUtf8("basinDelineationTab"))
        self.processLog2GroupBox = QtGui.QGroupBox(self.basinDelineationTab)
        self.processLog2GroupBox.setGeometry(QtCore.QRect(10, 94, 431, 251))
        self.processLog2GroupBox.setObjectName(_fromUtf8("processLog2GroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.processLog2GroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.delineateButton = QtGui.QToolButton(self.processLog2GroupBox)
        self.delineateButton.setEnabled(False)
        self.delineateButton.setObjectName(_fromUtf8("delineateButton"))
        self.gridLayout.addWidget(self.delineateButton, 1, 1, 1, 1)
        self.processLog2TextEdit = QtGui.QTextEdit(self.processLog2GroupBox)
        self.processLog2TextEdit.setReadOnly(True)
        self.processLog2TextEdit.setObjectName(_fromUtf8("processLog2TextEdit"))
        self.gridLayout.addWidget(self.processLog2TextEdit, 0, 0, 1, 2)
        self.delineateProgressBar = QtGui.QProgressBar(self.processLog2GroupBox)
        self.delineateProgressBar.setProperty("value", 0)
        self.delineateProgressBar.setObjectName(_fromUtf8("delineateProgressBar"))
        self.gridLayout.addWidget(self.delineateProgressBar, 1, 0, 1, 1)
        self.outletsGroupBox = QtGui.QGroupBox(self.basinDelineationTab)
        self.outletsGroupBox.setGeometry(QtCore.QRect(10, 10, 661, 78))
        self.outletsGroupBox.setObjectName(_fromUtf8("outletsGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.outletsGroupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.outletsLineEdit = QtGui.QLineEdit(self.outletsGroupBox)
        self.outletsLineEdit.setReadOnly(True)
        self.outletsLineEdit.setObjectName(_fromUtf8("outletsLineEdit"))
        self.horizontalLayout_14.addWidget(self.outletsLineEdit)
        self.selectOutletsButton = QtGui.QToolButton(self.outletsGroupBox)
        self.selectOutletsButton.setObjectName(_fromUtf8("selectOutletsButton"))
        self.horizontalLayout_14.addWidget(self.selectOutletsButton)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_14)
        self.clipMaskCheckBox = QtGui.QCheckBox(self.outletsGroupBox)
        self.clipMaskCheckBox.setObjectName(_fromUtf8("clipMaskCheckBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.clipMaskCheckBox)
        self.createSubBasinCheckBox = QtGui.QCheckBox(self.outletsGroupBox)
        self.createSubBasinCheckBox.setObjectName(_fromUtf8("createSubBasinCheckBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.createSubBasinCheckBox)
        self.label = QtGui.QLabel(self.basinDelineationTab)
        self.label.setGeometry(QtCore.QRect(450, 90, 211, 251))
        self.label.setAutoFillBackground(True)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/SphyPreProcess/delineation.png")))
        self.label.setScaledContents(True)
        self.label.setMargin(5)
        self.label.setObjectName(_fromUtf8("label"))
        self.Tab.addTab(self.basinDelineationTab, _fromUtf8(""))
        self.stationsTab = QtGui.QWidget()
        self.stationsTab.setObjectName(_fromUtf8("stationsTab"))
        self.processLog3GroupBox = QtGui.QGroupBox(self.stationsTab)
        self.processLog3GroupBox.setGeometry(QtCore.QRect(10, 79, 381, 261))
        self.processLog3GroupBox.setObjectName(_fromUtf8("processLog3GroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.processLog3GroupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.processLog3TextEdit = QtGui.QTextEdit(self.processLog3GroupBox)
        self.processLog3TextEdit.setReadOnly(True)
        self.processLog3TextEdit.setObjectName(_fromUtf8("processLog3TextEdit"))
        self.verticalLayout_5.addWidget(self.processLog3TextEdit)
        self.stationsButton = QtGui.QToolButton(self.processLog3GroupBox)
        self.stationsButton.setEnabled(True)
        self.stationsButton.setObjectName(_fromUtf8("stationsButton"))
        self.verticalLayout_5.addWidget(self.stationsButton)
        self.groupBox = QtGui.QGroupBox(self.stationsTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 661, 61))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.stationsLineEdit = QtGui.QLineEdit(self.groupBox)
        self.stationsLineEdit.setReadOnly(True)
        self.stationsLineEdit.setObjectName(_fromUtf8("stationsLineEdit"))
        self.horizontalLayout_16.addWidget(self.stationsLineEdit)
        self.selectStationsButton = QtGui.QToolButton(self.groupBox)
        self.selectStationsButton.setObjectName(_fromUtf8("selectStationsButton"))
        self.horizontalLayout_16.addWidget(self.selectStationsButton)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.label_2 = QtGui.QLabel(self.stationsTab)
        self.label_2.setGeometry(QtCore.QRect(400, 80, 271, 261))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/SphyPreProcess/stations.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Tab.addTab(self.stationsTab, _fromUtf8(""))
        self.meteoTab = QtGui.QWidget()
        self.meteoTab.setObjectName(_fromUtf8("meteoTab"))
        self.forcingGroupBox = QtGui.QGroupBox(self.meteoTab)
        self.forcingGroupBox.setGeometry(QtCore.QRect(10, 10, 361, 51))
        self.forcingGroupBox.setObjectName(_fromUtf8("forcingGroupBox"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.forcingGroupBox)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.precFlagCheckBox = QtGui.QCheckBox(self.forcingGroupBox)
        self.precFlagCheckBox.setChecked(True)
        self.precFlagCheckBox.setObjectName(_fromUtf8("precFlagCheckBox"))
        self.horizontalLayout_17.addWidget(self.precFlagCheckBox)
        self.tempFlagCheckBox = QtGui.QCheckBox(self.forcingGroupBox)
        self.tempFlagCheckBox.setChecked(True)
        self.tempFlagCheckBox.setObjectName(_fromUtf8("tempFlagCheckBox"))
        self.horizontalLayout_17.addWidget(self.tempFlagCheckBox)
        self.precGroupBox = QtGui.QGroupBox(self.meteoTab)
        self.precGroupBox.setGeometry(QtCore.QRect(10, 70, 361, 131))
        self.precGroupBox.setObjectName(_fromUtf8("precGroupBox"))
        self.precDBRadioButton = QtGui.QRadioButton(self.precGroupBox)
        self.precDBRadioButton.setGeometry(QtCore.QRect(10, 20, 69, 17))
        self.precDBRadioButton.setChecked(True)
        self.precDBRadioButton.setObjectName(_fromUtf8("precDBRadioButton"))
        self.precFilesGroupBox = QtGui.QGroupBox(self.precGroupBox)
        self.precFilesGroupBox.setGeometry(QtCore.QRect(10, 40, 341, 85))
        self.precFilesGroupBox.setObjectName(_fromUtf8("precFilesGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.precFilesGroupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.precLocFileLineEdit = QtGui.QLineEdit(self.precFilesGroupBox)
        self.precLocFileLineEdit.setReadOnly(True)
        self.precLocFileLineEdit.setObjectName(_fromUtf8("precLocFileLineEdit"))
        self.horizontalLayout_18.addWidget(self.precLocFileLineEdit)
        self.precLocToolButton = QtGui.QToolButton(self.precFilesGroupBox)
        self.precLocToolButton.setObjectName(_fromUtf8("precLocToolButton"))
        self.horizontalLayout_18.addWidget(self.precLocToolButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.precDataFileLineEdit = QtGui.QLineEdit(self.precFilesGroupBox)
        self.precDataFileLineEdit.setReadOnly(True)
        self.precDataFileLineEdit.setObjectName(_fromUtf8("precDataFileLineEdit"))
        self.horizontalLayout_19.addWidget(self.precDataFileLineEdit)
        self.precDataToolButton = QtGui.QToolButton(self.precFilesGroupBox)
        self.precDataToolButton.setObjectName(_fromUtf8("precDataToolButton"))
        self.horizontalLayout_19.addWidget(self.precDataToolButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.precCSVRadioButton = QtGui.QRadioButton(self.precGroupBox)
        self.precCSVRadioButton.setGeometry(QtCore.QRect(110, 20, 145, 17))
        self.precCSVRadioButton.setObjectName(_fromUtf8("precCSVRadioButton"))
        self.processLog4GroupBox = QtGui.QGroupBox(self.meteoTab)
        self.processLog4GroupBox.setGeometry(QtCore.QRect(380, 10, 291, 331))
        self.processLog4GroupBox.setObjectName(_fromUtf8("processLog4GroupBox"))
        self.processLog4TextEdit = QtGui.QTextEdit(self.processLog4GroupBox)
        self.processLog4TextEdit.setGeometry(QtCore.QRect(10, 23, 271, 271))
        self.processLog4TextEdit.setReadOnly(True)
        self.processLog4TextEdit.setObjectName(_fromUtf8("processLog4TextEdit"))
        self.forcingToolButton = QtGui.QToolButton(self.processLog4GroupBox)
        self.forcingToolButton.setGeometry(QtCore.QRect(200, 300, 81, 21))
        self.forcingToolButton.setObjectName(_fromUtf8("forcingToolButton"))
        self.forcingProgressBar = QtGui.QProgressBar(self.processLog4GroupBox)
        self.forcingProgressBar.setGeometry(QtCore.QRect(10, 300, 181, 21))
        self.forcingProgressBar.setProperty("value", 0)
        self.forcingProgressBar.setObjectName(_fromUtf8("forcingProgressBar"))
        self.tempGroupBox = QtGui.QGroupBox(self.meteoTab)
        self.tempGroupBox.setGeometry(QtCore.QRect(10, 200, 361, 141))
        self.tempGroupBox.setObjectName(_fromUtf8("tempGroupBox"))
        self.tempDBRadioButton = QtGui.QRadioButton(self.tempGroupBox)
        self.tempDBRadioButton.setGeometry(QtCore.QRect(10, 20, 69, 17))
        self.tempDBRadioButton.setChecked(True)
        self.tempDBRadioButton.setObjectName(_fromUtf8("tempDBRadioButton"))
        self.tempCSVRadioButton = QtGui.QRadioButton(self.tempGroupBox)
        self.tempCSVRadioButton.setGeometry(QtCore.QRect(110, 20, 145, 17))
        self.tempCSVRadioButton.setObjectName(_fromUtf8("tempCSVRadioButton"))
        self.tempFilesGroupBox = QtGui.QGroupBox(self.tempGroupBox)
        self.tempFilesGroupBox.setGeometry(QtCore.QRect(10, 46, 341, 85))
        self.tempFilesGroupBox.setObjectName(_fromUtf8("tempFilesGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tempFilesGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.tempLocFileLineEdit = QtGui.QLineEdit(self.tempFilesGroupBox)
        self.tempLocFileLineEdit.setReadOnly(True)
        self.tempLocFileLineEdit.setObjectName(_fromUtf8("tempLocFileLineEdit"))
        self.horizontalLayout_20.addWidget(self.tempLocFileLineEdit)
        self.tempLocToolButton = QtGui.QToolButton(self.tempFilesGroupBox)
        self.tempLocToolButton.setObjectName(_fromUtf8("tempLocToolButton"))
        self.horizontalLayout_20.addWidget(self.tempLocToolButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.tempDataFileLineEdit = QtGui.QLineEdit(self.tempFilesGroupBox)
        self.tempDataFileLineEdit.setReadOnly(True)
        self.tempDataFileLineEdit.setObjectName(_fromUtf8("tempDataFileLineEdit"))
        self.horizontalLayout_21.addWidget(self.tempDataFileLineEdit)
        self.tempDataToolButton = QtGui.QToolButton(self.tempFilesGroupBox)
        self.tempDataToolButton.setObjectName(_fromUtf8("tempDataToolButton"))
        self.horizontalLayout_21.addWidget(self.tempDataToolButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.Tab.addTab(self.meteoTab, _fromUtf8(""))
        self.horizontalLayoutWidget = QtGui.QWidget(SphyPreProcessDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 213, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.newButton = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.newButton.setObjectName(_fromUtf8("newButton"))
        self.horizontalLayout_7.addWidget(self.newButton)
        self.openButton = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.horizontalLayout_7.addWidget(self.openButton)
        self.saveAsButton = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.saveAsButton.setObjectName(_fromUtf8("saveAsButton"))
        self.horizontalLayout_7.addWidget(self.saveAsButton)

        self.retranslateUi(SphyPreProcessDialog)
        self.Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SphyPreProcessDialog)

    def retranslateUi(self, SphyPreProcessDialog):
        SphyPreProcessDialog.setWindowTitle(_translate("SphyPreProcessDialog", "SPHY preprocessor", None))
        self.foldersGroupBox.setTitle(_translate("SphyPreProcessDialog", "Folder selection", None))
        self.databaseLabel.setText(_translate("SphyPreProcessDialog", "Database", None))
        self.databaseFolderButton.setText(_translate("SphyPreProcessDialog", "Select database folder", None))
        self.processedModelDataLabel.setText(_translate("SphyPreProcessDialog", "Processed model data", None))
        self.resultsFolderButton.setText(_translate("SphyPreProcessDialog", "Select output folder", None))
        self.pcrasterBinFolderLabel.setText(_translate("SphyPreProcessDialog", "PCRaster bin folder", None))
        self.pcrasterBinFolderButton.setText(_translate("SphyPreProcessDialog", "Select PCRaster bin folder", None))
        self.periodProcessGroupBox.setTitle(_translate("SphyPreProcessDialog", "Meteorological forcing period to process", None))
        self.startDateLabel.setText(_translate("SphyPreProcessDialog", "Start date", None))
        self.startDateEdit.setDisplayFormat(_translate("SphyPreProcessDialog", "dd-MMM-yyyy", None))
        self.endDateLabel.setText(_translate("SphyPreProcessDialog", "End date", None))
        self.endDateEdit.setDisplayFormat(_translate("SphyPreProcessDialog", "dd-MMM-yyyy", None))
        self.coordinateSystemGroupBox.setTitle(_translate("SphyPreProcessDialog", "Coordinate system", None))
        self.utmInfoLineEdit.setPlainText(_translate("SphyPreProcessDialog", "Select the UTM WGS84 coordinate system for your area. Click the show UTM map\n"
"button to identify the corresponding UTM zone for your model area.", None))
        self.utmLabel.setText(_translate("SphyPreProcessDialog", "WGS84 UTM zone", None))
        self.utmNRadioButton.setText(_translate("SphyPreProcessDialog", "N", None))
        self.utmSRadioButton.setText(_translate("SphyPreProcessDialog", "S", None))
        self.showUTMMapButton.setText(_translate("SphyPreProcessDialog", "show UTM map", None))
        self.Tab.setTabText(self.Tab.indexOf(self.generalTab), _translate("SphyPreProcessDialog", "General settings", None))
        self.selectAreagroupBox.setTitle(_translate("SphyPreProcessDialog", "Select area", None))
        self.selectAreaButton.setText(_translate("SphyPreProcessDialog", "Click to select area", None))
        self.showBackgroundMapcheckBox.setText(_translate("SphyPreProcessDialog", "Show background layers", None))
        self.areaPropertiesGroupBox.setTitle(_translate("SphyPreProcessDialog", "Area properties", None))
        self.areaSizeLabel.setText(_translate("SphyPreProcessDialog", "Area size [km2]", None))
        self.xminLabel.setText(_translate("SphyPreProcessDialog", "xmin", None))
        self.xmaxLabel.setText(_translate("SphyPreProcessDialog", "xmax", None))
        self.columnsLabel.setText(_translate("SphyPreProcessDialog", "columns", None))
        self.yminLabel.setText(_translate("SphyPreProcessDialog", "ymin", None))
        self.ymaxLabel.setText(_translate("SphyPreProcessDialog", "ymax", None))
        self.rowsLabel.setText(_translate("SphyPreProcessDialog", "rows", None))
        self.numberCellsLabel.setText(_translate("SphyPreProcessDialog", "Number of cells", None))
        self.spatialResolutionLabel.setText(_translate("SphyPreProcessDialog", "Set spatial resolution [m]", None))
        self.calculateAreaPropsButton.setText(_translate("SphyPreProcessDialog", "Re-calculate area properties", None))
        self.selectedAreaMapLabel.setText(_translate("SphyPreProcessDialog", "Selected area", None))
        self.createModelCloneButton.setText(_translate("SphyPreProcessDialog", "Create model clone", None))
        self.Tab.setTabText(self.Tab.indexOf(self.areaSelectionTab), _translate("SphyPreProcessDialog", "Area selection", None))
        self.modulesGroupBox.setTitle(_translate("SphyPreProcessDialog", "Modules to process", None))
        self.glacierModCheckBox.setText(_translate("SphyPreProcessDialog", "Glaciers", None))
        self.snowModCheckBox.setText(_translate("SphyPreProcessDialog", "Snow", None))
        self.groundwaterModCheckBox.setText(_translate("SphyPreProcessDialog", "Groundwater", None))
        self.routingModCheckBox.setText(_translate("SphyPreProcessDialog", "Routing", None))
        self.dynamicVegModCheckBox.setText(_translate("SphyPreProcessDialog", "Dynamic vegetation", None))
        self.lakesModCheckBox.setText(_translate("SphyPreProcessDialog", "Lakes", None))
        self.reservorisModCheckBox.setText(_translate("SphyPreProcessDialog", "Reservoirs", None))
        self.sedimentModCheckBox.setText(_translate("SphyPreProcessDialog", "Sediment", None))
        self.mapsGroupBox.setTitle(_translate("SphyPreProcessDialog", "Maps to process", None))
        self.processLog1GroupBox.setTitle(_translate("SphyPreProcessDialog", "Process log", None))
        self.createInitialMapsToolButton.setText(_translate("SphyPreProcessDialog", "Create initial maps", None))
        self.Tab.setTabText(self.Tab.indexOf(self.modulesTab), _translate("SphyPreProcessDialog", "Modules", None))
        self.processLog2GroupBox.setTitle(_translate("SphyPreProcessDialog", "Process log", None))
        self.delineateButton.setText(_translate("SphyPreProcessDialog", "Delineate basin", None))
        self.outletsGroupBox.setTitle(_translate("SphyPreProcessDialog", "Basin settings", None))
        self.selectOutletsButton.setText(_translate("SphyPreProcessDialog", "Select outlet(s) shapefile", None))
        self.clipMaskCheckBox.setText(_translate("SphyPreProcessDialog", "Clip to basin mask", None))
        self.createSubBasinCheckBox.setText(_translate("SphyPreProcessDialog", "Create sub-basins", None))
        self.Tab.setTabText(self.Tab.indexOf(self.basinDelineationTab), _translate("SphyPreProcessDialog", "Basin delineation", None))
        self.processLog3GroupBox.setTitle(_translate("SphyPreProcessDialog", "Process log", None))
        self.stationsButton.setText(_translate("SphyPreProcessDialog", "Create stations", None))
        self.groupBox.setTitle(_translate("SphyPreProcessDialog", "Stations for time-series output", None))
        self.selectStationsButton.setText(_translate("SphyPreProcessDialog", "Select station(s) shapefile", None))
        self.Tab.setTabText(self.Tab.indexOf(self.stationsTab), _translate("SphyPreProcessDialog", "Stations", None))
        self.forcingGroupBox.setTitle(_translate("SphyPreProcessDialog", "Meteorological forcings to process", None))
        self.precFlagCheckBox.setText(_translate("SphyPreProcessDialog", "Precipitation", None))
        self.tempFlagCheckBox.setText(_translate("SphyPreProcessDialog", "Temperature", None))
        self.precGroupBox.setTitle(_translate("SphyPreProcessDialog", "Precipitation", None))
        self.precDBRadioButton.setText(_translate("SphyPreProcessDialog", "Database", None))
        self.precFilesGroupBox.setTitle(_translate("SphyPreProcessDialog", "CSV files", None))
        self.precLocToolButton.setText(_translate("SphyPreProcessDialog", "Select location file", None))
        self.precDataToolButton.setText(_translate("SphyPreProcessDialog", "Select data file", None))
        self.precCSVRadioButton.setText(_translate("SphyPreProcessDialog", "User defined station data", None))
        self.processLog4GroupBox.setTitle(_translate("SphyPreProcessDialog", "Process log", None))
        self.forcingToolButton.setText(_translate("SphyPreProcessDialog", "Create forcing", None))
        self.tempGroupBox.setTitle(_translate("SphyPreProcessDialog", "Temperature", None))
        self.tempDBRadioButton.setText(_translate("SphyPreProcessDialog", "Database", None))
        self.tempCSVRadioButton.setText(_translate("SphyPreProcessDialog", "User defined station data", None))
        self.tempFilesGroupBox.setTitle(_translate("SphyPreProcessDialog", "CSV files", None))
        self.tempLocToolButton.setText(_translate("SphyPreProcessDialog", "Select location file", None))
        self.tempDataToolButton.setText(_translate("SphyPreProcessDialog", "Select data file", None))
        self.Tab.setTabText(self.Tab.indexOf(self.meteoTab), _translate("SphyPreProcessDialog", "Meteorological forcing", None))
        self.newButton.setText(_translate("SphyPreProcessDialog", "New Project", None))
        self.openButton.setText(_translate("SphyPreProcessDialog", "Open project", None))
        self.saveAsButton.setText(_translate("SphyPreProcessDialog", "Save As", None))

import resources_rc
